- name: markosamuli.aws-tools
  src: https://github.com/markosamuli/ansible-aws-tools
  version: v1.0.1
- name: markosamuli.gcloud
  src: https://github.com/markosamuli/ansible-gcloud
  version: v1.1.0
- name: markosamuli.golang
  src: https://github.com/markosamuli/ansible-golang
  version: v1.0.0
- name: markosamuli.nvm
  src: https://github.com/markosamuli/ansible-nvm
  version: v1.1.0
- name: markosamuli.packer
  src: https://github.com/markosamuli/ansible-packer
  version: v1.0.0
- name: markosamuli.pyenv
  src: https://github.com/markosamuli/ansible-pyenv
  version: v1.2.0
- name: markosamuli.terraform
  src: https://github.com/markosamuli/ansible-terraform
  version: v1.1.0
- name: markosamuli.vagrant
  src: https://github.com/markosamuli/ansible-vagrant
  version: v1.0.0
