#!/usr/bin/env bash

# Commands
run_playbook=1  # Run playbook as default command
syntax_check=0  # Run command to check syntax
list_tags=0     # Run command to list tags

# Setup options
install_roles=1
install_ansible=1
install_homebrew=1

# Environment configuration
deploy_env="local"

# Force use of Ansible from Homebrew
ansible_homebrew=1

# Ansible playbook options
ansible_playbook="playbooks/main.yml"
ansible_roles="playbooks/roles"
ansible_tags=""
ansible_verbose=0
ansible_become=0

###
# Print error into STDERR
###
function error {
    echo "$@" 1>&2
}

###
# Print usage help
###
function show_help {
    echo "Usage: $0"
    echo " -h         Show this help"
    echo " -v         Verbose mode"
    echo " -n         Do not run Ansible playbook"
    echo " -q         Do not install Ansible requirements"
    echo " -l         List available Ansible tags"
    echo " -s         Ansible playbook syntax check"
    echo " -t TAGS    Run Ansible with the given comma separated list of tags"
}

###
# Install dependencies on macOS
###
function install_macos_dependencies {
    if [ "$install_homebrew" == "1" ]; then
        if test ! $(which gcc); then
            install_xcode_cli
        fi
        if test ! "$(which brew)"; then
            install_homebrew
        fi
    fi
    if [ "$install_ansible" == "1" ]; then
        if test ! "$(which ansible)"; then
            install_ansible_with_homebrew
        elif [ "$(brew --prefix ansible)" == "" ]; then
            install_ansible_with_homebrew
        fi
    fi
}

###
# Install Xcode Command Line Tools
###
function install_xcode_cli {
    local errmsg="Failed to install Xcode Command Line Tools"
    echo "*** Installing Xcode Command Line Tools..."
    xcode-select --install \
        || { error "${errmsg}"; exit 1; }
}

###
# Install Homebrew
###
function install_homebrew {
    local url="https://raw.githubusercontent.com"
    url="${url}/Homebrew/install/master/install"
    local errmsg="Failed to install Homebrew"
    echo "*** Installing Homebrew..."
    ruby -e "$(curl -fsSL ${url})" \
        || { error "${errmsg}"; exit 1; }
}

###
# Install Ansible with Homebrew
###
function install_ansible_with_homebrew {
    local errmsg="Failed to install Ansible"
    echo "*** Installing Ansible with Homebrew..."
    brew install ansible \
        || { error "${errmsg}"; exit 1; }
}

###
# Install Ansible roles
###
function install_ansible_roles {
    local errmsg="Failed to install Ansible roles"
    echo "*** Installing Ansible roles..."
    $(ansible_bin_prefix)ansible-galaxy install \
        -r requirements.yml \
        -p ${ansible_roles} \
        || { error "${errmsg}"; exit 1; }
}

###
# Ansible binary prefix
###
function ansible_bin_prefix {
    if [ "${ansible_homebrew}" == "1" ]; then
        echo "$(brew --prefix ansible)/bin/"
    fi
}

###
# Run Ansible playbook
###
function run_ansible_playbook {

    local ansible_opts=""

    if [ "${ansible_verbose}" == "1" ]; then
        ansible_opts="-v ${ansible_opts}"
    fi

    if [ "${ansible_tags}" != "" ]; then
        ansible_opts="--tags=${ansible_tags} ${ansible_opts}"
    fi

    $(ansible_bin_prefix)ansible-playbook ${ansible_playbook} \
        $(ansible_inventory) \
        ${ansible_opts}

}

###
# Check Ansible playbook syntax
###
function check_ansible_playbook_syntax {
    $(ansible_bin_prefix)ansible-playbook ${ansible_playbook} \
        --syntax-check
}

###
# Ansible inventory options
###
function ansible_inventory {
    local ansible_opts=""
    if [ "${deploy_env}" != "" ]; then
        deploy_env_err="Could not find inventory file for ${deploy_env}"
        [ -e "inventory/${deploy_env}" ] \
            || { error "${deploy_env_err}"; exit 1; }
        ansible_opts="-i inventory/${deploy_env} ${ansible_opts}"
    fi
    echo ${ansible_opts}
}

### 
# List tags available in Ansible playbooks
###
function ansible_playbook_list_tags {
    $(ansible_bin_prefix)ansible-playbook ${ansible_playbook} \
        $(ansible_inventory) \
        --list-tags
}

###
# Setup dependencies
###
function setup_dependencies {

    if test "$(uname)" = "Darwin"; then
        install_macos_dependencies
    elif test "$(uname)" = "Linux"; then
        error "Linux is not currently supported."
        exit 1
    fi

    if test ! "$(which ansible)"; then
        error "You system is not supported yet."
        exit 1
    fi

    local ansible_err="Ansible not found"
    $(ansible_bin_prefix)ansible --version \
        || { error "${ansible_err}"; exit 1; }
}

###
# Parse boolean options
###
function parse_bool {
    case $1 in
        1|true|True|TRUE|yes)
            echo "1"
            return 0
            ;;
        0|false|False|FALSE|no)
            echo "0"
            return 0
            ;;
        *)
            return 1
            ;;
    esac
}

# # Parse long command line arguments
# POSITIONAL=()
# while [[ $# -gt 0 ]]
# do
# key="$1"
# case $key in
#     --ansible-homebrew)
#     ansible_homebrew="$(parse_bool $2)"
#     shift # past argument
#     shift # past value
#     ;;
#     *)    # unknown option
#     POSITIONAL+=("$1") # save it in an array for later
#     shift # past argument
#     ;;
# esac
# done
# set -- "${POSITIONAL[@]}" # restore positional parameters

###
# Parse command line options
###
while getopts ":hcnqlsvt:" opt; do
    case $opt in
        h)
            show_help
            exit 0
            ;;
        n)
            run_playbook=0
            ;;
        q)
            install_roles=0
            install_ansible=0
            install_homebrew=0
            ;;
        l)
            list_tags=1
            run_playbook=0
            ;;
        s)
            syntax_check=1
            run_playbook=0
            ;;
        v)
            ansible_verbose=1
            ;;
        t)
            ansible_tags=$OPTARG
            ;;
        \?)
            error "Invalid option: -$OPTARG"
            show_help
            exit 1
            ;;
        :)
            error "Option -$OPTARG requires an argument"
            exit 1
            ;;
    esac
done

setup_dependencies

if [ "$install_roles" == "1" ]; then
    install_ansible_roles
fi

if [ "$list_tags" == "1" ]; then
    ansible_playbook_list_tags
elif [ "$syntax_check" == "1" ]; then
    check_ansible_playbook_syntax
elif [ "$run_playbook" == "1" ]; then
    run_ansible_playbook
fi
