#!/usr/bin/env bash

passed=0
failed=0
total=0

# Run playbook
run_playbook() {
    local playbook=$1
    local status="failed"
    echo "*** Playbook: $playbook"
    total=$((total + 1))
    ansible-playbook \
        -i inventory/local "playbooks/$playbook" |
        grep -q 'changed=0.*failed=0' && status="passed"
    if [ "${status}" == "passed" ]; then
        echo "Idempotence test: pass on playbook $playbook"
        passed=$((passed + 1))
        return 0
    else
        echo "Idempotence test: fail on playbook $playbook"
        failed=$((failed + 1))
        return 1
    fi
}

# Parse included playbooks from the main.yml file
get_playbooks() {
    grep -e "- import_playbook: .*\.yml" playbooks/main.yml |
        grep -v vagrant.yml |
        sed 's/- import_playbook: //'
}

playbooks=$(get_playbooks)
for playbook in $playbooks; do
    run_playbook "$playbook"
done

if [ "$failed" -gt "0" ]; then
    echo "$failed / $total idempotence tests failed"
    exit 1
fi

if [ "$passed" -lt "$total" ]; then
    echo "$passed / $total idempotence tests passed"
    exit 1
fi

echo "All $passed / $total idempotence tests passed"
