---
- name: Terminus
  hosts: all
  tags: terminus
  tasks:
    - name: Check if Terminus has been installed
      stat:
        path: /Applications/Terminus.app
      register: terminus_st
      changed_when: false

    - name: Install Terminus
      homebrew_cask:
        name: terminus
      when: not terminus_st.stat.exists
